<?php
use Drupal\indexing_study\Entity\AisStudy;
use Drupal\indexing_study\Entity\AisDocument;

function indexing_study_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['ais_study'])) {
    $bundles['node']['ais_study']['class'] = AisStudy::class;
  }
  if (isset($bundles['node']['ais_document'])) {
    $bundles['node']['ais_document']['class'] = AisDocument::class;
  }
}

